spring:
  application:
    name: zipkin-client
  zipkin:
    base-url: http://localhost:8791
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 8792
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8759/eureka/,http://localhost:8760/eureka/,http://localhost:8761/eureka/

