spring:
  application:
    name: api-gateway
server:
  port: 8888
zuul:
  routes:
    test:
      path: /test/**
      #url:  http://www.baidu.com
      serviceId: eureka-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8759/eureka/,http://localhost:8760/eureka/,http://localhost:8761/eureka/


