spring:
  application:
    name: zipkin-server
server:
  port: 8791
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8759/eureka/,http://localhost:8760/eureka/,http://localhost:8761/eureka/