spring:
  application:
    name: eureka-server
server:
  port: 8759
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/,http://localhost:8761/eureka/



