spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiezhaokun/config-center
          search-paths: /**
          username: xiezhaokun
          password: xie2011048683

server:
  port: 8765

management:
  security:
    enabled: false
